/**
 * Generates ATTRIBUTION.md from the icons we actually ship. Pure: same input → same text.
 */

import type { IconEntry } from '../../src/icons/types.ts';

export type AttributionInput = {
  icons: readonly Pick<IconEntry, 'author' | 'authorName' | 'authorUrl' | 'license'>[];
  source: { repo: string; commit: string };
};

export function generateAttribution({ icons, source }: AttributionInput): string {
  const byAuthor = new Map<
    string,
    { name: string; url?: string; license: string; count: number }
  >();
  for (const icon of icons) {
    const existing = byAuthor.get(icon.author);
    if (existing) {
      existing.count += 1;
    } else {
      const entry: { name: string; url?: string; license: string; count: number } = {
        name: icon.authorName,
        license: icon.license,
        count: 1,
      };
      if (icon.authorUrl) entry.url = icon.authorUrl;
      byAuthor.set(icon.author, entry);
    }
  }
  const authors = [...byAuthor.values()].sort((a, b) => a.name.localeCompare(b.name, 'en'));

  const lines: string[] = [
    '# Attribution',
    '',
    '<!-- GENERATED by scripts/build-shipped-icons.ts — do not edit by hand. -->',
    '',
    'Icons in this game come from [game-icons.net](https://game-icons.net), vendored from',
    `${source.repo} at commit \`${source.commit}\`.`,
    'They are licensed under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) unless marked CC0.',
    '',
  ];
  if (authors.length === 0) {
    lines.push('_No icons are currently shipped._', '');
  } else {
    for (const a of authors) {
      const link = a.url ? ` ([${a.url}](${a.url}))` : '';
      const cc0 = a.license === 'CC0-1.0' ? ' — CC0' : '';
      lines.push(
        `- Icons made by ${a.name}. Available on https://game-icons.net${link}${cc0} — ${a.count} icon${a.count === 1 ? '' : 's'}`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}
